version: "2.1"
services:
  chrome:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    shm_size: "3gb"
    #gjhghjhjgjghgh